#!/usr/bin/python
# -*- coding: utf-8 -*-   


def multiples(nb_max):
    total = 0
    for x in range(nb_max):
        if (x % 3 == 0 or x % 5 == 0):
            total += x
    return total

#result of the problem
print multiples(1000)
