#!/usr/bin/python
# -*- coding: utf-8 -*-   

#A bit long but works
def is_div(nb):
    for x in range(1,20):
        if ((nb % x) != 0):
            return True
    return False

nb = 1
while (is_div(nb)):
    nb += 1
print nb
    
