#!/usr/bin/python
# -*- coding: utf-8 -*-   

w = True
a = 0
b = 0
c = 0
while w:
    for a in range(1, 100):
        for b in range(1, 100):
            for c in range(1, 100):
                if (pow(a, 2) + pow(b, 2) == pow(c, 2) and a + b + c == 1000):
                    w = False
                print a, b, c
                print a*a + b*b,  c*c
                if (a*a + b*b == c*c):
                    print "LLKJLKL"
print a, b, c
             
